use crate::windows::{FuncPatcher, patches::*};

pub static KERNEL_TARGETS: [(&'static str, Option<FuncPatcher>); 34] = [
  ("GetFileAttributesExA", None),
  ("GetFileAttributesA", None),
  ("GetFileAttributesExW", None),
  ("GetFileAttributesW", None),
  ("SetFileAttributesW", None),
  ("CreateDirectoryW", None),
  ("RemoveDirectoryW", None),
  ("DeleteFileW", None),
  ("GetCurrentDirectoryA", None),
  ("GetCurrentDirectoryW", None),
  ("SetCurrentDirectoryA", None),
  ("SetCurrentDirectoryW", None),
  ("ExitProcess", None),
  ("CreateProcessInternalW", None),
  ("MoveFileA", None),
  ("MoveFileW", None),
  ("MoveFileExA", None),
  ("MoveFileExW", None),
  ("MoveFileWithProgressA", None),
  ("MoveFileWithProgressW", None),
  ("CopyFileExW", None),
  ("GetPrivateProfileStringA", None),
  ("GetPrivateProfileStringW", None),
  ("GetPrivateProfileSectionA", None),
  ("GetPrivateProfileSectionW", None),
  ("WritePrivateProfileStringA", None),
  ("WritePrivateProfileStringW", None),
  ("GetFullPathNameA", None),
  ("GetFullPathNameW", None),
  ("FindFirstFileExW", None),
  ("LoadLibraryExA", None),
  ("LoadLibraryExW", None),
  ("GetModuleFileNameA", None),
  ("GetModuleFileNameW", None),
];

pub static WIN_8_OR_LATER_KERNEL_TARGETS: [(&'static str, Option<FuncPatcher>); 1] =
  [("CopyFile2", None)];

pub static NT_TARGETS: [(&'static str, Option<FuncPatcher>); 11] = [
  ("NtQueryFullAttributesFile", None),
  ("NtQueryAttributesFile", None),
  ("NtQueryDirectoryFile", Some(nt_query_directory_file)),
  ("NtQueryDirectoryFileEx", Some(nt_query_directory_file_ex)),
  ("NtQueryObject", None),
  ("NtQueryInformationFile", None),
  ("NtQueryInformationByName", None),
  ("NtOpenFile", Some(nt_open_file)),
  ("NtCreateFile", Some(nt_create_file)),
  ("NtClose", None),
  ("NtTerminateProcess", None),
];
