[profile.default]
slow-timeout = { period = "30s" }

[test-groups]
serial = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(java::)'
test-group = 'serial'

[[profile.default.overrides]]
filter = 'test(integration::windows::java::relative_redirect)'
retries = 3
