[package]
name = "demo"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]

[dev-dependencies]
clap = { version = "4.5.39", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
